# Petite introduction (ou recapitulatif) de Python

Avant de pouvoir accomplir quoi que ce soit en AI ou machine learning, nous avons besoin d’un langage de programation pour le faire. Dans ce notebook, nous passerons en revue la programmation en Python. Nous ne couvrirons pas certaines des conventions de programmation les plus basiques, et supposons que l’étudiant connaisse au moins les notions de variables, de fonctions, etc...

## Qu'est-ce que Python?
---
Python est un langage informatique à usage général * interprété * de haut niveau. Un langage interprété est un langage dont le code n'a pas besoin d'être compilé avant son exécution. C'est assez différent des langages tels que C, C ++ et Fortran, où l'on doit compiler du code lisible par l'homme en instructions machine.

En Python, tout le code est exécuté par "l'interpréteur" de Python, un programme principal qui lit notre code lisible par l'homme et le traduit en code machine lors de son exécution. Cela permet un certain nombre de fonctionnalités dynamiques qui ne sont pas prises en charge dans les langues compilées. Par exemple, le bloc-notes Jupyter que nous utilisons maintenant ne serait pas possible sans un langage interprété tel que Python.

In [1]:
# Un exemple d'exécution de code interprété ...!
# (Les commentaires sont faits en utilisant le symbole #)
2 + 2

4

Python permet également le "typage dynamique": les types de variable ne sont pas attribués par le codeur, mais sont déduits directement par l'interpréteur Python. Cela  donne au programmeur la possibilité de prototyper rapidement, mais peut parfois nécessiter du code supplémentaire pour vous assurer que vous avez le bon type! Regardons un exemple de frappe dynamique.

In [2]:
## Une variable peut être de tout type.
x = 2     # x est un integer...
x = 2.0   # x est un float...
x = 'hi'  # x est un string...

## Cela peut causer des problemes!
#x = 2 + x

Comme nous pouvons le constater, si nous ne faisons pas attention, la réaffectation des variables peut poser des problèmes. Nous devons donc veiller à ne pas trop abuser de cette fonctionnalité. Nous pouvons aussi voir que nous avons eu notre première erreur! L'interpréteur Python signalera les erreurs dès qu'elles se produisent. Dans un langage compilé tel que C, le compilateur aurait renvoyé une erreur lors de la compilation car il aurait détecté ce type de collision en tant qu'erreur de compilation. Cependant, pour Python, comme nous ne connaissons que le type de variable au moment de l'exécution, nous avons plutôt une erreur d'exécution au moment de ce type d'incompatibilité de type.

Cependant, en résumant le typage et l'adressage des variables, Python évite bon nombre des erreurs d'exécution qui apparaissent souvent dans les langages compilés. Par exemple, nous ne rencontrerons pas d'erreurs de pointeur, de fuites de mémoire ou d'autres erreurs d'exécution (erreurs de segmentation) souvent rencontrées en C et C ++. Ne pas avoir à résoudre les problèmes de mémoire est un avantage considérable par rapport à la vérification des types. Pour des comparaisons spécifiques entre Python et d'autres language, [consultez cette page] (https://www.python.org/doc/essays/comparisons/). Notamment

> *"Python code is typically 3-5 times shorter than equivalent Java code, it is often 5-10 times shorter than equivalent C++ code! Anecdotal evidence suggests that one Python programmer can finish in two months what two C++ programmers can't complete in a year."* -- Python Software Foundation

## Python 101
---
Commençons notre recapitulatif sur le codage Python en passant en revue de nombreuses structures et variables  que nous utilisons dans les programmes. Que diriez-vous d'un "Hello World"?

In [3]:
print('Hello World!')

Hello World!


Tres simple, non? On peut acceder a la documentation pour "print"

In [4]:
help(print)

Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



Les commandes d’impression peuvent prendre différents types d’objets en entrée et pas seulement des chaînes. L'objet doit simplement avoir une option d'affichage définie.

In [5]:
print(2.0)     # ... float
print(2)       # ... integer
print('c')     # ... string
print(print)   # ..."a function handle"

2.0
2
c
<built-in function print>


Essayons maintenant un peu d’arithmétique. Toutes les opérations mathématiques normales se comportent comme prévu.

In [6]:
## Set some variables !
a = 2
b = 3
print('1)', a, '+', b, '=', a+b)
print('2)', a, '-', b, '=', a-b)
print('3)', a, '*', b, '=', a*b)
print('4)', a, '/', b, '=', a/b)
print('5)', a, '^', b, '=', a**b)
print('6)', a, '%', b, '=', a%b)

1) 2 + 3 = 5
2) 2 - 3 = -1
3) 2 * 3 = 6
4) 2 / 3 = 0.6666666666666666
5) 2 ^ 3 = 8
6) 2 % 3 = 2


Regardons maintenant certaines structures de flux de contrôle. Voyons d’abord le format du code de branchement, par exemple: * si-alors-sinon *. Ces instructions fonctionnent en Python comme vous le voudriez dans n'importe quelle autre langue que vous connaissez. Cependant, nous devons faire attention à la syntaxe. Contrairement aux langages tels que C / C ++, où les espaces sont très fluides et laissés au programmeur via un backeting, l’interpréteur Python requiert une indentation stricte du code au lieu d’un bracketing.

In [7]:
some_value = -1

# Branch based on the sign of the value
if some_value == 0:
    print('Value is equal to 0.')
elif some_value > 0:
    print('Value is positive.')
else:
    print('Value is negative.')

Value is negative.


Notez que Python n'inclut pas de structure de contrôle `switch` explicite comme en C / C ++. Au lieu de cela, on utilise une échelle d'instructions `if-elif-elif -...` pour atteindre le même objectif, comme nous le voyons ci-dessus. Depuis Python 2.5, Python a également un opérateur ternaire ...

In [8]:
some_value = -2

# Ternary operator is given as
#    a if condition else b
print('Value >= 0') if some_value >= 0 else print('Value is negative.')

Value is negative.


Nous allons maintenant examiner les boucles de base en Python. En pratique, la boucle la plus commune avec laquelle vous vous connecterez est la boucle `for`. Jetons un coup d'oeil à un exemple.

In [9]:
n_loops = 3

# We need an object to loop over. `range(0,x)` returns an iterator over the range [0,...,x-1]. 
for loop in range(0,n_loops):
    print('Loop #',loop)

Loop # 0
Loop # 1
Loop # 2


En Python, vous pouvez effectuer une boucle sur un objet itérable, pas seulement des valeurs numériques. Jetons un coup d'oeil à un exemple simple en créant une liste de valeurs.

In [10]:
# Iterate over a list of string values
list_of_strings = ['just', 'a', 'list', 'of', 'strings']

for string in list_of_strings:
    print(string)

just
a
list
of
strings


Fait intéressant, en raison de la nature du typage dynamique en Python, nos listes ne sont pas limitées à un seul type. Une liste peut contenir un nombre quelconque d'objets, chacun d'un type différent.

In [11]:
# Iterate over whatever
list_of_whatever = ['just', 42, 'things', 3.14, print, ('i', 'guess')]

for thing in list_of_whatever:
    print(thing)

just
42
things
3.14
<built-in function print>
('i', 'guess')


---

---
## Ex 1: Calculer n!
Par exemple, écrivons une fonction pour calculer la factorielle d’un entier positif donné, $n! = n\times(n-1)\times(n-2)\times\cdots$, et $0! = 1$. Définissons cela comme une fonction afin de pouvoir l'utiliser à nouveau plus tard.

In [12]:
## Your solution below...
def factorial(n):
    result = 1
    for i in range(1,int(n+1)):
        result *= i
    return result

### Validation


In [13]:
assert factorial(0) == 1
assert factorial(6) == 720
assert factorial(5) == 120
assert factorial(10) == 3628800
factorial(-1)
factorial(2.5)
print("Tests Passed !")

Tests Passed !


---

---

## Python connait les maths!
Voyons maintenant comment effectuer un certain nombre d'opérations mathématiques de base dans Julia, y compris des exemples d'algèbre linéaire. Voyons d’abord quelques opérations mathématiques scalaires simples.

Dans ce cas, nous devrons importer des fonctionnalités supplémentaires du paquet `math`, un module Python standard fourni avec la distribution Python principale. La fonctionnalité d’importation est gérée de la même manière que C \ C ++, toutefois, il faut tenir compte de certaines considérations relatives aux espaces de noms.

Par exemple, si nous voulons utiliser la fonction exponentielle du paquet `math`, nous avons plusieurs façons de procéder, en fonction de nos souhaits en tant que programmeurs.

1. La methode simple:
```python
>>> import math
>>> math.exp(1)
2.718281828459045
```

2. Renomer le package namespace en plus court:
```python
>>> import math as m
>>> m.exp(1)
2.718281828459045
```

3. Importer seulement certaines parties du package:
```python
>>> from math import exp
>>> exp(1)
2.718281828459045
```

Il n'y a pas une seule bonne façon d'aborder cela, il vous suffit de trouver une approche qui répond à vos besoins et rend votre code concis et lisible.

In [14]:
import math as m   # Just making an easy short name

# Lets look at a basic right triangle...
#      |\
#      | \  h = ?
# a=3  |  \
#      |___\
#       b=1
#

a = 3
b = 1
ang_ab = 90

# Calculate the hypotenuse
h = m.sqrt(a**2 + b**2)

# Find remaining angles
ang_bh = m.degrees(m.asin(a / h))
ang_ah = 180 - ang_ab - ang_bh

# Show results
print('      %0.1f' % ang_ah)
print('       | \\')
print('       |  \\')
print('       |   \\')      
print('a = ',a,'|    \\  h = %0.1f' % h)
print('       |     \\')
print('       |      \\')
print('       |       \\')
print('       |90__%0.1f\\' % ang_bh)  
print('         b =',b)

      18.4
       | \
       |  \
       |   \
a =  3 |    \  h = 3.2
       |     \
       |      \
       |       \
       |90__71.6\
         b = 1


So, we can do simple trigonometry. But we can also do logarithms, exponentials, etc. We also have some specific constants which are defined for us in `math`.

In [15]:
m.log(m.exp(m.pi))   # m.log() defaults to natural log

3.141592653589793

## List, dictionaires, sets & tuples

Python inclut plusieurs types de conteneurs intégrés: listes, dictionnaires, ensembles et t-uples.

**list**: Une liste est l'équivalent Python d'un tableau, mais est redimensionnable et peut contenir des éléments de différents types:

In [16]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'foo'     # Lists can contain elements of different types
print(xs)         # Prints "[3, 1, 'foo']"
xs.append('bar')  # Add a new element to the end of the list
print(xs)         # Prints "[3, 1, 'foo', 'bar']"
x = xs.pop()      # Remove and return the last element of the list
print(x, xs)      # Prints "bar [3, 1, 'foo']"

[3, 1, 2] 2
2
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


**Slicing**: En plus d'accéder aux éléments d'une liste à la fois, Python fournit une syntaxe concise pour accéder aux sous-listes. c'est ce qu'on appelle le découpage en tranches (Slicing):

In [17]:
nums = list(range(5))     # range is a built-in function that creates a list of integers
print(nums)               # Prints "[0, 1, 2, 3, 4]"
print(nums[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(nums[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(nums[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(nums[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(nums[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
nums[2:4] = [8, 9]        # Assign a new sublist to a slice
print(nums)               # Prints "[0, 1, 8, 9, 4]"

[0, 1, 2, 3, 4]
[2, 3]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]


**dictionaries:** Un dictionnaire stocke des paires (clé, valeur): Vous pouvez l'utiliser comme ceci:

In [18]:
d = {'cat': 'cute', 'dog': 'furry'}  # Create a new dictionary with some data
print(d['cat'])       # Get an entry from a dictionary; prints "cute"
print('cat' in d)     # Check if a dictionary has a given key; prints "True"
d['fish'] = 'wet'     # Set an entry in a dictionary
print(d['fish'])      # Prints "wet"
# print(d['monkey'])  # KeyError: 'monkey' not a key of d
print(d.get('monkey', 'N/A'))  # Get an element with a default; prints "N/A"
print(d.get('fish', 'N/A'))    # Get an element with a default; prints "wet"
del d['fish']         # Remove an element from a dictionary
print(d.get('fish', 'N/A')) # "fish" is no longer a key; prints "N/A"

d = {'person': 2, 'cat': 4, 'spider': 8}
for animal in d:
    legs = d[animal]
    print('A %s has %d legs' % (animal, legs))
# Prints "A person has 2 legs", "A cat has 4 legs", "A spider has 8 legs"

cute
True
wet
N/A
wet
N/A
A person has 2 legs
A cat has 4 legs
A spider has 8 legs


**set**: Un ensemble est une collection non ordonnée d'éléments distincts. Comme exemple simple, considérons ce qui suit:

In [19]:
animals = {'cat', 'dog'}
print('cat' in animals)   # Check if an element is in a set; prints "True"
print('fish' in animals)  # prints "False"
animals.add('fish')       # Add an element to a set
print('fish' in animals)  # Prints "True"
print(len(animals))       # Number of elements in a set; prints "3"
animals.add('cat')        # Adding an element that is already in the set does nothing
print(len(animals))       # Prints "3"
animals.remove('cat')     # Remove an element from a set
print(len(animals))       # Prints "2"

animals = {'cat', 'dog', 'fish'}
for idx, animal in enumerate(animals):
    print('#%d: %s' % (idx + 1, animal))
# Prints "#1: fish", "#2: dog", "#3: cat"

True
False
True
3
3
2
#1: fish
#2: dog
#3: cat


**tuple**: Un t-uple est une liste de valeurs ordonnée (immuable). Un tuple est à bien des égards similaire à une liste; L'une des différences les plus importantes est que les n-uplets peuvent être utilisés comme clés dans les dictionnaires et comme éléments d'ensembles, alors que les listes ne le peuvent pas. Voici un exemple trivial:

In [20]:
d = {(x, x + 1): x for x in range(10)}  # Create a dictionary with tuple keys
t = (5, 6)        # Create a tuple
print(type(t))    # Prints "<class 'tuple'>"
print(d[t])       # Prints "5"
print(d[(1, 2)])  # Prints "1"

<class 'tuple'>
5
1


## Statistique en Python

Maintenant, disons que vous voulez faire des statistiques. Peut-être que vous voulez commencer à tirer des échantillons d'une distribution particulière ... ou peut-être que vous voulez vérifier son entropie? Comme pour tout ce qui se passe en Python, vous devez supposer que cela a déjà été implémenté, et chercher un package... en particulier, pour tout ce qui est statistique, voila scipy.stats: [(Documentation complète ici)](https://docs.scipy.org/doc/scipy-0.18.1/reference/stats.html).

In [21]:
import scipy.stats as stat

# Calclulate the entropy of a Laplace distribution
mu  = 1
sig = 3
e = stat.laplace.entropy(loc=mu,scale=sig)    # Differential Entropy...

# What about the higher-order moments?
m, v, s, k = stat.laplace.stats(loc=mu,scale=sig,moments='mvsk')

print('---- true dist. stats----')
print('Mean           = %0.3f' % m)
print('Variance       = %0.3f' % v)
print('Skew           = %0.3f' % s)
print('Kurtosis       = %0.3f' % k)
print('Diff. Entropy  = %0.3f' % e)

# We can generate data from this distribution
data = stat.laplace.rvs(loc=mu, scale=sig, size=1000)

# Fit parameters
mu_fit, sig_fit = stat.laplace.fit(data)

# See values
m, v, s, k = stat.laplace.stats(loc=mu_fit,scale=sig_fit,moments='mvsk')
e = stat.laplace.entropy(loc=mu_fit,scale=sig_fit)

print('---- est dist. stats----')
print('Mean           = %0.3f' % m)
print('Variance       = %0.3f' % v)
print('Skew           = %0.3f' % s)
print('Kurtosis       = %0.3f' % k)
print('Diff. Entropy  = %0.3f' % e)

---- true dist. stats----
Mean           = 1.000
Variance       = 18.000
Skew           = 0.000
Kurtosis       = 3.000
Diff. Entropy  = 2.792
---- est dist. stats----
Mean           = 1.004
Variance       = 17.940
Skew           = 0.000
Kurtosis       = 3.000
Diff. Entropy  = 2.790


## Algebre lineaire en Python: numpy

L'algebre lineaire et la manipulation de tableau sera fondamentale dans ce cours. Pour cela, les listes, dictionaires, etc... ne sont pas vraiment adaptés, car il ne nous permettent pas de traiter les tableaux comme des matrices; et il nous faudra utiliser l'un des outils les plus important de la galaxie python: les numpy arrays!

In [22]:
# Make use of numpy
import numpy as np

a = np.array([1, 2, 3])   # Create a rank 1 array
print(type(a))            # Prints "<class 'numpy.ndarray'>"
print(a.shape)            # Prints "(3,)"
print(a[0], a[1], a[2])   # Prints "1 2 3"
a[0] = 5                  # Change an element of the array
print(a)                  # Prints "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array
print(b.shape)                     # Prints "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

<class 'numpy.ndarray'>
(3,)
1 2 3
[5 2 3]
(2, 3)
1 2 4


Numpy nous permet de creer des tableaux de toutes sorte:

In [23]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)              # Prints "[[ 0.  0.]
                      #          [ 0.  0.]]"

b = np.ones((1,2))    # Create an array of all ones
print(b)              # Prints "[[ 1.  1.]]"

c = np.full((2,2), 7)  # Create a constant array
print(c)               # Prints "[[ 7.  7.]
                       #          [ 7.  7.]]"

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              # Prints "[[ 1.  0.]
                      #          [ 0.  1.]]"

e = np.random.random((2,2))  # Create an array filled with random values
print(e)                     # Might print "[[ 0.91940167  0.08143941]
                             #               [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.96835199 0.02483254]
 [0.41437541 0.97929303]]


Numpy offre plusieurs méthodes pour indexer dans des tableaux.

Tranchage (slicing): similaires aux listes Python, les tableaux numpy peuvent être tranchés. Comme les tableaux peuvent être multidimensionnels, vous devez spécifier une tranche pour chaque dimension du tableau.

In [24]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]

# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


Vous pouvez également combiner l'indexation d'entiers avec l'indexation de tranches. Cependant, cela produira un tableau de rang inférieur à celui d'origine. Notez que cela est assez différent de la façon dont MATLAB gère le découpage en matrice:

In [25]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


### Maths et arrays
Les fonctions mathématiques de base fonctionnent élément par tableau sur les tableaux et sont disponibles à la fois en tant que surcharge d’opérateur et en tant que fonctions dans le module numpy:

In [26]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

# Elementwise sum; both produce the array
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(x + y)
print(np.add(x, y))

# Elementwise difference; both produce the array
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(x - y)
print(np.subtract(x, y))

# Elementwise product; both produce the array
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(x * y)
print(np.multiply(x, y))

# Elementwise division; both produce the array
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))

# Elementwise square root; produces the array
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


Notez que contrairement à MATLAB, * est une multiplication par élément, pas une multiplication par matrice. Nous utilisons plutôt la fonction point pour calculer les produits internes des vecteurs, pour multiplier un vecteur par une matrice et pour multiplier des matrices. dot est disponible à la fois en tant que fonction dans le module numpy et en tant que méthode d'instance d'objets tableau.

In [27]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


On peut aussi utiliser @ comme symbole de multiplication matricielle, ce qui permet de garder une notation agreable.

In [28]:
# Inner product of vectors; both produce 219
print(v@w)

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x@v)

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x@y)

219
[29 67]
[[19 22]
 [43 50]]


### Numpy Broadcasting

 La diffusion (numpy Broadcasting) est un mécanisme puissant qui permet à numpy de travailler avec des tableaux de formes différentes lorsqu’il effectue des opérations arithmétiques. Nous avons fréquemment un tableau plus petit et un tableau plus grand, et nous souhaitons utiliser le tableau plus petit plusieurs fois pour effectuer certaines opérations sur le tableau le plus grand.
Par exemple, supposons que nous voulions ajouter un vecteur constant à chaque ligne d'une matrice. Nous pourrions le faire comme ceci:

In [29]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

# Now y is the following
# [[ 2  2  4]
#  [ 5  5  7]
#  [ 8  8 10]
#  [11 11 13]]
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


Cela marche; Toutefois, lorsque la matrice x est très grande, le calcul d’une boucle explicite en Python peut être lent. Notez que l'ajout du vecteur v à chaque ligne de la matrice x revient à former une matrice vv en empilant plusieurs copies de v verticalement, puis en effectuant la somme élémentaire de x et vv. Nous pourrions implémenter cette approche comme ceci:

In [30]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


La diffusion Numpy nous permet d'effectuer ce calcul sans créer réellement plusieurs copies de v. Considérez cette version, en utilisant la diffusion:

In [31]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)  # Prints "[[ 2  2  4]
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [32]:
import numpy as np

# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
# an output of shape (3, 2), which is the outer product of v and w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
# giving the following matrix:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column. Gives the following matrix:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3), producing the
# following array:
# [[ 2  4  6]
#  [ 8 10 12]]
print(x * 2)

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 2  4  6]
 [ 8 10 12]]


## Classes
---
Comme C / C ++ et Java, Python prend en charge les structures de classe. Cependant, ce n'est pas un "langage orienté objet" dans le vrai sens du terme. Il ne prend pas en charge l’encapsulation stricte, c’est-à-dire la privatisation des données d’objet. Cependant, il prend en charge la commodité des classes de toute autre manière. Jetons un coup d'oeil à un exemple. Ici, nous définissons une classe pour un * Agent *, qui se déplace sur une grille 2D, en évaluant l'utilitaire qui l'entoure.

In [33]:
class Agent:
    """
        A simple class which defines an `agent`, some decision making
        entity which wants to maximize its own reward.
    """    
    def __init__(self, utility=0, position=(0.0,0.0), utility_func = None, step_size = 1.0):
        """
            The initialization function gets called by the interpreter
            every time a new object of the Agent class gets created.
            
            :param utility: Agent's current utility value.
            :param utility_func: Function with which to evaluate the utility of the agent. 
                                 The funciton `utility_func` takes an (x,y) coordinate and
                                 reports a utility.
            :param position: Agent's current position (x,y)
            
        """
        self.utility = utility
        self.position = position
        self.utility_func = utility_func
        self.history = dict(position = [], utility = [])
        self.step_size = step_size
    
    def __repr__(self):
        """
            This function gets called whenever the interpreter needs a "formal" 
            string representation (error logs, etc.)
        """
        return "Agent<p:%s, u:%s>" %(self.position, self.utility)
    
    def __str__(self):
        """
            This function gets called by the interpreter whenever
            there needs to be a "user friendly" 
            string description of the Agent object (e.g. `print(Agent())`).
        """
        return "Agent @ %s [u=%s]" % (self.position, self.utility)
    
    def record_state(self):
        """
            Store the current state of the agent in a queue.
        """
        self.history['position'].append(self.position)
        self.history['utility'].append(self.utility)
    
    def move_up(self):
        """
            Increment the Y coordinate of the agent.
        """
        self.record_state()
        self.position = (self.position[0], self.position[1]+self.step_size)
        self.utility = self.evaluate_utility()
        
    def move_down(self):
        """
            Decrement the Y coordinate of the agent.
        """
        self.record_state()
        self.position = (self.position[0], self.position[1]-self.step_size)
        self.utility = self.evaluate_utility()
        
    def move_left(self):
        """
            Decrement the X coordinate of the agent
        """
        self.record_state()
        self.position = (self.position[0]-self.step_size, self.position[1])
        self.utility = self.evaluate_utility()
        
    def move_right(self):
        """
            Increment the X coordinate of the agent
        """
        self.record_state()
        self.position = (self.position[0]+self.step_size, self.position[1])
        self.utility = self.evaluate_utility()
        
    def evaluate_utility(self, offset=(0.0, 0.0)):
        """
            Get the utility function relative to the current agent
            location. Optinally, evaluate at some offset from the agent.
            
            :param offset: Tuple of (x,y) coordinates with which to offset the agent
                           position to evaluate the utility.
            :return: A numeric value for the utility at the evaluated point
        """
        if self.utility_func == None:
            return 0   # Simple Agent with simple utility
        else:
            return self.utility_func((self.position[0]+offset[0],
                                      self.position[1]+offset[1]))
        


Pour utiliser la classe, il suffit d'initialiser un objet avec le constructeur de l'agent. Dans ce cas, toutes les valeurs par défaut sont utilisées. De plus, nous ne spécifions pas encore de fonction utilitaire pour l'espace dans lequel l'agent réside. Nous pouvons appeler des fonctions de la classe d'agent pour cet agent en particulier et voir ce qu'il en est.

In [34]:
# Instantiate the Agent object, `heri`...
henri = Agent()
print('[t = 0]', henri, 'History:', henri.history)

# Try moving around a bit and look at the history
henri.move_up()
print('[t = 1]', henri, 'History:', henri.history)

henri.move_left()
print('[t = 2]', henri, 'History:', henri.history)

henri.move_up()
print('[t = 3]', henri, 'History:', henri.history)

[t = 0] Agent @ (0.0, 0.0) [u=0] History: {'position': [], 'utility': []}
[t = 1] Agent @ (0.0, 1.0) [u=0] History: {'position': [(0.0, 0.0)], 'utility': [0]}
[t = 2] Agent @ (-1.0, 1.0) [u=0] History: {'position': [(0.0, 0.0), (0.0, 1.0)], 'utility': [0, 0]}
[t = 3] Agent @ (-1.0, 2.0) [u=0] History: {'position': [(0.0, 0.0), (0.0, 1.0), (-1.0, 1.0)], 'utility': [0, 0, 0]}


Avec la façon dont nous avons écrit la classe `Agent`, nous pouvons également lui transmettre n'importe quelle fonction utilitaire basée sur la position. Pensons à mettre Henri dans une sorte de paysage. Dans ce cas, qu’en est-il d’un simple utilitaire gaussien 2D isométrique qui possède un seul point de maximisation, donc quelque chose qui suit une fonction simple comme ...
$$U(\mathbf{x}) = \frac{1}{2\pi\sigma} e ^{-\frac{(\mathbf{x} - \boldsymbol{\mu})^T(\mathbf{x} - \boldsymbol{\mu})}{2\sigma^2} }$$

In [35]:
from math import exp, sqrt, pi

def gaussian_utility(position, mean=(0.0,0.0), sig=1.0):
    """
        A simple utility function, essentially just an iid 
        multivariate normal.
    """
    # Get the variance
    v = sig**2
    # Calculate distance from mean
    d = (position[0] - mean[0], position[1] - mean[1])
    dTd = d[0]**2/v + d[1]**2/v
    # Scaling
    scale = 1/(2*pi*v)
    # Final computation
    utility = scale * exp(-0.5 * dTd)
    utility += 1e-12
        
    return utility

Maintenant que nous avons défini une fonction d’utilité, mettons Henri "sur le terrain", pour ainsi dire. Nous pouvons assigner cette fonction d’utilitaire à notre classe `Agent` au moyen d’une fonction ** lambda **. Une fonction lambda nous permet de définir un nouvel appel vers une fonction spécifique dans laquelle certains paramètres sont fixes et certains sont variables. Dans notre cas, nous voulons que les paramètres de la fonction d'utilité (la moyenne et l'écart type) restent fixes, tout en modifiant la position. Une définition de fonction lambda simple ressemble à l'exemple suivant.

```python
    >>> def foo(param1, param2):
    ...     return param1 + param2
    ...
    >>> foo_single_param = lambda value: foo(value, 4)
    >>> foo_single_param(2)
    6
```

Nous pouvons l'utiliser pour passer une fonction lambda en tant qu'utilitaire de l'agent. Voyons comment faire cela, ci-dessous

In [36]:
# Define some parameters for the utility function
utility_peak = (2.0,2.0)
utility_sigma = 1.0

utility_lambda = lambda position: gaussian_utility(position, mean=utility_peak, sig=utility_sigma)

henri = Agent(utility_func = utility_lambda)
print('[t = 0]', henri)

# Try moving around a bit and look at the history
henri.move_up()
print('[t = 1]', henri)

henri.move_right()
print('[t = 2]', henri)

henri.move_up()
print('[t = 3]', henri)

henri.move_right()
print('[t = 4]', henri)

henri.move_up()
print('[t = 5]', henri)

[t = 0] Agent @ (0.0, 0.0) [u=0]
[t = 1] Agent @ (0.0, 1.0) [u=0.013064233285684922]
[t = 2] Agent @ (1.0, 1.0) [u=0.05854983152531917]
[t = 3] Agent @ (1.0, 2.0) [u=0.09653235263105392]
[t = 4] Agent @ (2.0, 2.0) [u=0.15915494309289535]
[t = 5] Agent @ (2.0, 3.0) [u=0.09653235263105392]


---

---

## Ex. 2 Stochastic Climber
Disons que nous avons un alpiniste et qu'il veut gravir le plus haut sommet. Cependant, un fort brouillard s'est abattu sur la vallée dans laquelle il réside. Il ne peut voir que le sol juste devant lui. Il sait que s'il monte toujours le chemin à chaque étape, il arrivera à un sommet ... mais probablement pas au sommet le plus haut. Au lieu de cela, il envisage de prendre une stratégie stochastique alternative.

À chaque intervalle de temps, il regarde les chemins en face de lui: N, S, E et W. Il décolle ensuite dans une direction aléatoire, dont la probabilité est proportionnelle aux pentes qui l’entourent. Il pense que cela lui donnera au moins une chance d'arriver au plus haut sommet.

Écrivez une classe qui hérite de la classe `Agent` et l’étend dans une classe` StochasticClimber`. Ecrivez une fonction `climb` qui prend le nombre de pas de temps en entrée et lance le grimpeur stochastique.

In [37]:
class StochasticClimber(Agent):    # Inherit from class Agent
    def climb(self, steps=1):
        """ Implement me !
            Run the stochastic climber for the specified number of steps
        """
        
        moves = np.array([self.move_right, self.move_left, self.move_up, self.move_down])
        
        for i in range(steps):
            slopes = np.array([max(0, self.evaluate_utility((self.step_size, 0.0))),
                               max(0, self.evaluate_utility((-self.step_size, 0.0))),
                               max(0, self.evaluate_utility((0.0, self.step_size))),
                               max(0, self.evaluate_utility((0.0, -self.step_size)))])

            proba = slopes / slopes.sum()
            move = np.random.choice(moves, p = proba)
            move()
            
        print(self)

*Solution*

In [38]:
# %load example2.py

### Validation

In [39]:
# Create some landscape for our climber. In this case we have a mountain range like the following
#          L
#          |
#          G
#        /  \
#       L    L
#
#    S   <-- start position
#
mountain_range = lambda p : gaussian_utility(p, mean=(2.0,2.0), sig = 0.1) + \
                            gaussian_utility(p, mean=(2.0,3.0), sig = 0.5) + \
                            gaussian_utility(p, mean=(1.0,1.0), sig = 0.5) + \
                            gaussian_utility(p, mean=(3.0,1.0), sig = 0.5)
            

# Run our climber
yves = StochasticClimber(utility_func=mountain_range, step_size=0.05)
yves.climb(steps=40000)

Agent @ (2.0500000000000007, 1.9500000000000008) [u=12.493602851397908]


---

---

## File I/O

Maintenant que nous avons effectué notre expérience avec `StochasticClimber`, disons que nous voulons enregistrer ces données sur disque pour une utilisation ultérieure. Peut-être pour une figure (par exemple, le prochain cahier). Ce serait bien de ne pas avoir à relancer l'expérience à chaque fois que nous voulons générer un nouveau chiffre! Jetons un coup d'œil aux E / S de fichier de base et voyons comment écrire un fichier Python ou CSV contenant nos résultats.

Dans le premier cas, examinons l'approche la plus simple, qui consiste à stocker l'intégralité de l'objet `yves` sur le disque. En utilisant le module `pickle`, nous pouvons stocker les données Python sur le disque et les recharger plus tard. Cela fonctionne à peu près de la même façon que les fichiers `mat` dans Matlab.

In [41]:
import pickle

# A simple example...
pickle.dump(yves, open('yves.p','wb'))

PicklingError: Can't pickle <function <lambda> at 0x7f11bac230d0>: attribute lookup <lambda> on __main__ failed

Cependant, notre fonction lambda ne peut pas être stockée sur le disque. Nous devrons plutôt stocker nos structures statiques (dans ce cas, l'historique).

In [42]:
with open('yves.p', 'wb') as pickle_file:
    pickle.dump(yves.history,pickle_file)

Ce bloc de contrôle "*` avec a comme f: `*" tente d'ouvrir le fichier spécifié et ferme en outre le descripteur de fichier à la fin du bloc. Ceci est pratique dans la mesure où il existe une erreur lors de l’entrée / sortie du fichier qui pourrait laisser un fichier suspendu ouvert.

Voyons maintenant ce que nous avons. Comme nous pouvons le voir ci-dessous, le fichier `yves.p` est maintenant enregistré sur le disque. Celui-ci contient l'historique `StochasticClimber`.

In [43]:
%ls

'Intro to Python.ipynb'   sine_cosine.pdf                  yves.p
 Visualization.ipynb      understanding-matplotlib.ipynb
 my_first_plot.pdf        yves.csv


Jetons maintenant un coup d'œil au chargement pour nous assurer qu'il est là.

In [44]:
with open('yves.p','rb') as pickle_file:
    yves_history_copy = pickle.load(pickle_file)
print(yves_history_copy)  # <-- Write a huge dataset below !

{'position': [(0.0, 0.0), (0.0, 0.05), (0.05, 0.05), (0.05, 0.1), (0.05, 0.05), (0.05, 0.0), (0.1, 0.0), (0.1, -0.05), (0.05, -0.05), (0.1, -0.05), (0.15000000000000002, -0.05), (0.15000000000000002, 0.0), (0.10000000000000002, 0.0), (0.05000000000000002, 0.0), (0.05000000000000002, 0.05), (0.10000000000000002, 0.05), (0.10000000000000002, 0.0), (0.10000000000000002, 0.05), (0.05000000000000002, 0.05), (0.05000000000000002, 0.1), (0.05000000000000002, 0.05), (0.05000000000000002, 0.1), (0.10000000000000002, 0.1), (0.10000000000000002, 0.05), (0.10000000000000002, 0.1), (0.10000000000000002, 0.15000000000000002), (0.10000000000000002, 0.10000000000000002), (0.15000000000000002, 0.10000000000000002), (0.15000000000000002, 0.15000000000000002), (0.10000000000000002, 0.15000000000000002), (0.10000000000000002, 0.10000000000000002), (0.10000000000000002, 0.05000000000000002), (0.10000000000000002, 0.10000000000000002), (0.10000000000000002, 0.05000000000000002), (0.10000000000000002, 0.1000

Nous prenons note de quelques aspects de cet exemple de cornichon. Plus précisément, les commandes `pick.dump ()` et `pickle.load ()` prennent des descripteurs de fichier, pas les noms de fichier eux-mêmes. Cela signifie que nous devons spécifier les options de lecture et d’écriture. Dans les deux cas, nous vidons toutes les données sous forme binaire (pas de chaînes), nous spécifions donc l'option 'b' lorsque nous utilisons `open ()`.

Maintenant, que faisons-nous si nous voulons écrire des données sur un disque accessibles par n’importe quel autre programme (par exemple, Excel, gnuplot, etc.)? Nous pouvons également écrire toutes ces données en tant que CSV. Jetons un coup d'oeil à cet exemple. Ici, nous allons utiliser des pandas pour le faire facilement.

In [45]:
import pandas as pd

# Create a new dictionary whose keys represent the headers (columns)
# of information that we would like to store in the CSV file.
yves_csv = dict(x=[], y=[], z=[])
yves_csv['x'] = [yves.history['position'][i][0] for i in range(0,len(yves.history['position']))]
yves_csv['y'] = [yves.history['position'][i][1] for i in range(0,len(yves.history['position']))]
yves_csv['z'] = yves.history['utility']

# Create a DataFrame object from a dictionary
df = pd.DataFrame.from_dict(yves_csv)
# Write to CSV format
df.to_csv("yves.csv", sep=',', header=True, index=False)  
%ls

'Intro to Python.ipynb'   sine_cosine.pdf                  yves.p
 Visualization.ipynb      understanding-matplotlib.ipynb
 my_first_plot.pdf        yves.csv


Et maintenant nous voyons le fichier CSV écrit sur le disque. Voilà!